import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Navbar from "@/components/Navbar";
import GlobalContextProvider from "@/context/GlobalContextProvider";
import {ToastContainer, toast} from 'react-toastify';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins px-4 md:px-10 lg:px-14 py-5 min-h-screen bg-slate-50`}
      >
        <GlobalContextProvider>
          <Navbar />
          <Suspense fallback={<loading />}>{children}</Suspense>
          <ToastContainer />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
